<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->delete();
        $cities = array(
            // Major cities in Alberta
            array('name' => "Calgary",'province_id' => 1,'status'=> 1),
            array('name' => "Edmonton",'province_id' => 1,'status'=> 1),
            array('name' => "Red Deer",'province_id' => 1,'status'=> 1),
            array('name' => "Lethbridge",'province_id' => 1,'status'=> 1),
            array('name' => "Sherwood Park",'province_id' => 1,'status'=> 1),
            array('name' => "Medicine Hat",'province_id' => 1,'status'=> 1),
            array('name' => "Saint Albert",'province_id' => 1,'status'=> 1),
            array('name' => "Grande Prairie",'province_id' => 1,'status'=> 1),
            array('name' => "Fort McMurray",'province_id' => 1,'status'=> 1),
            array('name' => "Airdrie",'province_id' => 1,'status'=> 1),
            array('name' => "Fort Saskatchewan",'province_id' => 1,'status'=> 1),
            array('name' => "Spruce Grove",'province_id' => 1,'status'=> 1),
            array('name' => "Cochrane",'province_id' => 1,'status'=> 1),
            array('name' => "Camrose",'province_id' => 1,'status'=> 1),
            array('name' => "Leduc",'province_id' => 1,'status'=> 1),
            // Major cities in British Columbia
            array('name' => "Vancouver",'province_id' => 2,'status'=> 1),
            array('name' => "Surrey",'province_id' => 2,'status'=> 1),
            array('name' => "Victoria",'province_id' => 2,'status'=> 1),
            array('name' => "Burnaby",'province_id' => 2,'status'=> 1),
            array('name' => "Richmond",'province_id' => 2,'status'=> 1),
            array('name' => "Abbotsford",'province_id' => 2,'status'=> 1),
            array('name' => "Coquitlam",'province_id' => 2,'status'=> 1),
            array('name' => "Kelowna",'province_id' => 2,'status'=> 1),
            array('name' => "Langley",'province_id' => 2,'status'=> 1),
            array('name' => "Delta",'province_id' => 2,'status'=> 1),
            array('name' => "Nanaimo",'province_id' => 2,'status'=> 1),
            array('name' => "Maple Ridge",'province_id' => 2,'status'=> 1),
            array('name' => "Kamloops",'province_id' => 2,'status'=> 1),
            array('name' => "White Rock",'province_id' => 2,'status'=> 1),
            array('name' => "New Westminster",'province_id' => 2,'status'=> 1),
            // Major cities in Manitoba
            array('name' => "Winnipeg",'province_id' => 3,'status'=> 1),
            array('name' => "Brandon",'province_id' => 3,'status'=> 1),
            array('name' => "Portage la Prairie",'province_id' => 3,'status'=> 1),
            array('name' => "Thompson",'province_id' => 3,'status'=> 1),
            array('name' => "Selkirk",'province_id' => 3,'status'=> 1),
            array('name' => "Steinbach",'province_id' => 3,'status'=> 1),
            array('name' => "Dauphin",'province_id' => 3,'status'=> 1),
            array('name' => "Winkler",'province_id' => 3,'status'=> 1),
            array('name' => "Morden",'province_id' => 3,'status'=> 1),
            array('name' => "The Pas",'province_id' => 3,'status'=> 1),
            array('name' => "Flin Flon",'province_id' => 3,'status'=> 1),
            array('name' => "Swan River",'province_id' => 3,'status'=> 1),
            array('name' => "Stonewall",'province_id' => 3,'status'=> 1),
            array('name' => "Altona",'province_id' => 3,'status'=> 1),
            array('name' => "Virden",'province_id' => 3,'status'=> 1),
            // Major cities in New Brunswick
            array('name' => "Saint John",'province_id' => 4,'status'=> 1),
            array('name' => "Moncton",'province_id' => 4,'status'=> 1),
            array('name' => "Fredericton",'province_id' => 4,'status'=> 1),
            array('name' => "Bathurst",'province_id' => 4,'status'=> 1),
            array('name' => "Miramichi",'province_id' => 4,'status'=> 1),
            array('name' => "Edmundston",'province_id' => 4,'status'=> 1),
            array('name' => "Campbellton",'province_id' => 4,'status'=> 1),
            array('name' => "Oromocto",'province_id' => 4,'status'=> 1),
            array('name' => "Grand Falls",'province_id' => 4,'status'=> 1),
            array('name' => "Shediac",'province_id' => 4,'status'=> 1),
            array('name' => "Caraquet",'province_id' => 4,'status'=> 1),
            array('name' => "Saint Stephen",'province_id' => 4,'status'=> 1),
            array('name' => "Dalhousie",'province_id' => 4,'status'=> 1),
            array('name' => "Sussex",'province_id' => 4,'status'=> 1),
            array('name' => "Sackville",'province_id' => 4,'status'=> 1),
            // Major cities in Newfoundland and Labrador
            array('name' => "Saint Johns",'province_id' => 5,'status'=> 1),
            array('name' => "Mount Pearl",'province_id' => 5,'status'=> 1),
            array('name' => "Conception Bay South",'province_id' => 5,'status'=> 1),
            array('name' => "Corner Brook",'province_id' => 5,'status'=> 1),
            array('name' => "Bay Roberts",'province_id' => 5,'status'=> 1),
            array('name' => "Grand Falls-Windsor",'province_id' => 5,'status'=> 1),
            array('name' => "Paradise",'province_id' => 5,'status'=> 1),
            array('name' => "Gander",'province_id' => 5,'status'=> 1),
            array('name' => "Goose Bay",'province_id' => 5,'status'=> 1),
            array('name' => "Labrador City",'province_id' => 5,'status'=> 1),
            array('name' => "Carbonear",'province_id' => 5,'status'=> 1),
            array('name' => "Stephenville",'province_id' => 5,'status'=> 1),
            array('name' => "Deer Lake",'province_id' => 5,'status'=> 1),
            array('name' => "Grand Bank",'province_id' => 5,'status'=> 1),
            array('name' => "Marystown",'province_id' => 5,'status'=> 1),
            // Major and local towns and cities in Northwest Territories
            array('name' => "Yellowknife",'province_id' => 6,'status'=> 1),
            array('name' => "Hay River",'province_id' => 6,'status'=> 1),
            array('name' => "Inuvik",'province_id' => 6,'status'=> 1),
            array('name' => "Fort Smith",'province_id' => 6,'status'=> 1),
            array('name' => "Norman Wells",'province_id' => 6,'status'=> 1),
            array('name' => "Tuktoyaktuk",'province_id' => 6,'status'=> 1),
            array('name' => "Aklavik",'province_id' => 6,'status'=> 1),
            array('name' => "Fort Liard",'province_id' => 6,'status'=> 1),
            // Major cities in Nova Scotia
            array('name' => "Halifax",'province_id' => 7,'status'=> 1),
            array('name' => "Dartmouth",'province_id' => 7,'status'=> 1),
            array('name' => "Sydney",'province_id' => 7,'status'=> 1),
            array('name' => "Glace Bay",'province_id' => 7,'status'=> 1),
            array('name' => "Truro",'province_id' => 7,'status'=> 1),
            array('name' => "New Glasgow",'province_id' => 7,'status'=> 1),
            array('name' => "Sydney Mines",'province_id' => 7,'status'=> 1),
            array('name' => "Kentville",'province_id' => 7,'status'=> 1),
            array('name' => "New Waterford",'province_id' => 7,'status'=> 1),
            array('name' => "Amherst",'province_id' => 7,'status'=> 1),
            array('name' => "Bridgewater",'province_id' => 7,'status'=> 1),
            array('name' => "Yarmouth",'province_id' => 7,'status'=> 1),
            array('name' => "North Sydney",'province_id' => 7,'status'=> 1),
            array('name' => "Greenwood",'province_id' => 7,'status'=> 1),
            array('name' => "Antigonish",'province_id' => 7,'status'=> 1),
            // Major cities in Nunavut
            array('name' => "Cambridge Bay",'province_id' => 8,'status'=> 1),
            array('name' => "Iqaluit",'province_id' => 8,'status'=> 1),
            array('name' => "Rankin Inlet",'province_id' => 8,'status'=> 1),
            array('name' => "Arviat",'province_id' => 8,'status'=> 1),
            array('name' => "Baker Lake",'province_id' => 8,'status'=> 1),
            array('name' => "Igloolik",'province_id' => 8,'status'=> 1),
            array('name' => "Kugluktuk",'province_id' => 8,'status'=> 1),
            array('name' => "Pangnirtung",'province_id' => 8,'status'=> 1),
            array('name' => "Gjoa Haven",'province_id' => 8,'status'=> 1),
            array('name' => "Clyde River",'province_id' => 8,'status'=> 1),
            array('name' => "Coral Harbour",'province_id' => 8,'status'=> 1),
            array('name' => "Taloyoak",'province_id' => 8,'status'=> 1),
            array('name' => "Repulse Bay",'province_id' => 8,'status'=> 1),
            array('name' => "Hall Beach",'province_id' => 8,'status'=> 1),
            array('name' => "Whale Cove",'province_id' => 8,'status'=> 1),
            // Major cities in Ontario
            array('name' => "Toronto",'province_id' => 9,'status'=> 1),
            array('name' => "Ottawa",'province_id' => 9,'status'=> 1),
            array('name' => "Hamilton",'province_id' => 9,'status'=> 1),
            array('name' => "Scarborough",'province_id' => 9,'status'=> 1),
            array('name' => "Mississauga",'province_id' => 9,'status'=> 1),
            array('name' => "Brampton",'province_id' => 9,'status'=> 1),
            array('name' => "Kitchener",'province_id' => 9,'status'=> 1),
            array('name' => "Etobicoke",'province_id' => 9,'status'=> 1),
            array('name' => "London",'province_id' => 9,'status'=> 1),
            array('name' => "Windsor",'province_id' => 9,'status'=> 1),
            array('name' => "Markham",'province_id' => 9,'status'=> 1),
            array('name' => "Vaughan",'province_id' => 9,'status'=> 1),
            array('name' => "Oshawa",'province_id' => 9,'status'=> 1),
            array('name' => "Richmond Hill",'province_id' => 9,'status'=> 1),
            array('name' => "Oakville",'province_id' => 9,'status'=> 1),
            // Major cities in Quebec
            array('name' => "Montreal",'province_id' => 10,'status'=> 1),
            array('name' => "Quebec City",'province_id' => 10,'status'=> 1),
            array('name' => "Laval",'province_id' => 10,'status'=> 1),
            array('name' => "Gatineau",'province_id' => 10,'status'=> 1),
            array('name' => "Longueuil",'province_id' => 10,'status'=> 1),
            array('name' => "Saguenay",'province_id' => 10,'status'=> 1),
            array('name' => "Levis",'province_id' => 10,'status'=> 1),
            array('name' => "Sherbrooke",'province_id' => 10,'status'=> 1),
            array('name' => "Trois-Rivieres",'province_id' => 10,'status'=> 1),
            array('name' => "Saint-Jean-sur-Richelieu",'province_id' => 10,'status'=> 1),
            array('name' => "Chicoutimi",'province_id' => 10,'status'=> 1),
            array('name' => "Drummondville",'province_id' => 10,'status'=> 1),
            array('name' => "Saint-jerome",'province_id' => 10,'status'=> 1),
            array('name' => "Granby",'province_id' => 10,'status'=> 1),
            array('name' => "Saint-Hyacinthe",'province_id' => 10,'status'=> 1),
            // Major and local towns and cities in Prince Edward Island
            array('name' => "Charlottetown",'province_id' => 11,'status'=> 1),
            array('name' => "Summerside",'province_id' => 11,'status'=> 1),
            array('name' => "Montague",'province_id' => 11,'status'=> 1),
            array('name' => "Kensington",'province_id' => 11,'status'=> 1),
            array('name' => "Souris",'province_id' => 11,'status'=> 1),
            array('name' => "Alberton",'province_id' => 11,'status'=> 1),
            // Major cities in Saskatchewan
            array('name' => "Saskatoon",'province_id' => 12,'status'=> 1),
            array('name' => "Regina",'province_id' => 12,'status'=> 1),
            array('name' => "Prince Albert",'province_id' => 12,'status'=> 1),
            array('name' => "Moose Jaw",'province_id' => 12,'status'=> 1),
            array('name' => "Lloydminster",'province_id' => 12,'status'=> 1),
            array('name' => "North Battleford",'province_id' => 12,'status'=> 1),
            array('name' => "Yorkton",'province_id' => 12,'status'=> 1),
            array('name' => "Swift Current",'province_id' => 12,'status'=> 1),
            array('name' => "Estevan",'province_id' => 12,'status'=> 1),
            array('name' => "Weyburn",'province_id' => 12,'status'=> 1),
            array('name' => "Melfort",'province_id' => 12,'status'=> 1),
            array('name' => "Humboldt",'province_id' => 12,'status'=> 1),
            array('name' => "Meadow Lake",'province_id' => 12,'status'=> 1),
            array('name' => "Melville",'province_id' => 12,'status'=> 1),
            array('name' => "Kindersley",'province_id' => 12,'status'=> 1),
            // Major cities in Yukon
            array('name' => "Whitehorse",'province_id' => 13,'status'=> 1),

        );
        DB::table('cities')->insert($cities);
    }
}